name: Build FLEX + Loader (arm64 iOS)
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout FLEX upstream
        uses: actions/checkout@v4
        with:
          repository: FLEXTool/FLEX
          path: flex-src

      - name: Create loader.m (fresh content)
        run: |
          mkdir -p loader-src
          cat > loader-src/loader.m <<'EOF'
          #include "loader.m"
          EOF

      - name: Show toolchain
        run: |
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-path

      - name: Build FLEX.framework for device
        working-directory: flex-src
        run: |
          set -e
          xcodebuild -project FLEX.xcodeproj -scheme FLEX -configuration Release -sdk iphoneos BUILD_DIR=build BUILD_ROOT=build clean build
          ls -la build/Release-iphoneos || true

      - name: Build Loader.dylib
        run: |
          SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
          clang -arch arm64 -isysroot "$SDK" -miphoneos-version-min=13.0 \
            -ObjC -fobjc-arc -dynamiclib loader-src/loader.m \
            -framework Foundation -framework UIKit \
            -o Loader.dylib
          file Loader.dylib || true
          lipo -info Loader.dylib || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flex-and-loader
          path: |
            flex-src/build/Release-iphoneos/FLEX.framework
            Loader.dylib
